#
# conda env create -f spot_conda_environment.yml
#
name: spot
dependencies:
  - python=3.13
  - pip
  - astropy>=7.2.0
  - scipy
  - matplotlib
  - pillow
  - pandas
  - pyqt
  - qtpy
  - python-dateutil
  - pyyaml
  - requests
  - ply

